myblog/myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index$', 'blog.views.index'),
    url(r'^register$', 'blog.views.register'),
    url(r'^(?P<p_id>[0-9]+)', 'blog.views.loggedin',name='logg'),
    url(r'^authcheck$', 'blog.views.authcheck'),
    url(r'^eventlist', 'blog.views.eventlist'),
    url(r'^profile','blog.views.profile'),
    url(r'^logout','blog.views.logout'),
    url(r'^editprofile','blog.views.edit'),
]

myblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
	title = models.CharField(max_length = 100)
	text = models.TextField()

	def __str__(self):
	  return self.title

	


class Comment(models.Model):
	name = models.CharField(max_length=20, null=True)
	text = models.TextField()
	post = models.ForeignKey(Post)
	

	def __str__(self):
	  return self.text


class UserProfile(models.Model):

    user = models.OneToOneField(User)
    name = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=30)

    def __str__(self):
        return '%s,%s,%s,%s' % (self.name, self.address, self.phone)

myblog/blog/forms.py
from django import forms
from .models import Post, Comment, UserProfile
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class RegForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('name', 'address', 'phone')

myblog/blog/views.py
from django.shortcuts import render_to_response
from django.core.context_processors import csrf
from django.contrib import auth
from django.http import HttpResponseRedirect, HttpResponse
from blog.models import Post, Comment, UserProfile
from django.template import RequestContext
from blog.forms import RegForm, CommentForm, UserProfileForm
from django.views.decorators.csrf import csrf_exempt
import pdb
from django.contrib.auth.models import User

# Create your views here.


def index(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('index.html', c)


@csrf_exempt
def edit(request):
    context=RequestContext(request)
    user = request.user
    profile = UserProfile.objects.get(user=user)
    if request.method == "POST":
      profile.name = request.POST['name']
      profile.address = request.POST['address']
      profile.phone = request.POST['phone']
      profile.save()
      return render_to_response('ok.html')
    return render_to_response('edit.html' ,{'profile':profile, "user": user},context)

@csrf_exempt
def authcheck(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = auth.authenticate(username=username, password=password)
    if user is not None:
        auth.login(request,user)
        return HttpResponseRedirect('/profile')
    else:
        return HttpResponse('Invalid login details')

@csrf_exempt
def loggedin(request,p_id):
    post = Post.objects.get(pk=p_id)
    if request.method == 'POST':
      form = CommentForm(request.POST)
      if form.is_valid():
        c = form.save(commit=False)
        c.name = request.user
        c.post =  post
        c.save()
    context = RequestContext(request)
    t = CommentForm()
    return render_to_response('loggedin.html',
              {'post': post, 'textform': t 
                 },context
               )
    
@csrf_exempt
def register(request):
    context = RequestContext(request)
    registered = False
    if request.method == 'POST':
        u_form = RegForm(data=request.POST)
        profile_form = UserProfileForm(request.POST)
        if u_form.is_valid() and profile_form.is_valid():
            user = u_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        if registered:
            return render_to_response('Registersuccess.html')
    u_form = RegForm()
    profile_form = UserProfileForm()
    return render_to_response('register.html',
        {'user_form': u_form, 
        'registered': registered,'profile_form': profile_form},
              context)

@csrf_exempt
def eventlist(request):
    post = Post.objects.all()
    context = RequestContext(request)
    return render_to_response('eventlist.html', {'post':post},context)

def profile(request):
    details = UserProfile.objects.get(user=request.user)
    return render_to_response("profile.html",
        {"full_name": details.name, 'address': details.address,
        'phone': details.phone})

def logout(request):
   auth.logout(request)
   return render_to_response('logout.html')

myblog/blog/templates/Registersuccess.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css/background' %}" />
<body style="background-image: url({% static "background.jpg" %})">
	<div style="margin-left:450px; margin-top:180px;">
<h1>You have successfully registerd</h1>
<td><a href="/index">Go Home</a></td>

myblog/blog/templates/edit.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'images/styles.css' %}" />
<div style="margin-left:480px; margin-top:210px;">
<h1>{{user.username}}'s home </h1>
<form action="/editprofile" method="post">
<br/>
<br/>
<br/>
<table>
<tr>
<td>Name:</td>
<td><input type="text" value="{{profile.name}}" name="name"></td>
</tr>
<tr>
<td>Address:</td>
<td><input type="text" value="{{profile.address}}" name="address"></td>
</tr>
<tr>
<td>Phone:</td>
<td><input type="text" value="{{profile.phone}}" name="phone"></td>
</tr>
</table>
<input type="submit" value="Update">&nbsp;&nbsp;<a href="/profile">Skip editting</a> 
</form>

myblog/blog/templates/eventlist.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css/background' %}" />
<body style="background-image: url({% static "background.jpg" %})">
	<div style="margin-left:480px; margin-top:180px;">
	<h1>EVENTS</h1>
<ol>
    {% for p in post %}
        <li><a href="{% url 'logg' p.id %}">{{ p.title }}</a></li>
        
    {% endfor %}
 </ol>

myblog/blog/templates/example.html
{% cycle 'row1' 'row2' as rowcolors silent %}
{% cycle rowcolors %}

myblog/blog/templates/index.html
<html>
<head>
<style>
body {
    margin-left: 200px;
    background: #5d9ab2 url("img_tree.png") no-repeat top left;
}

.container {
    text-align: center;
}

.center_div {
    border: 1px solid gray;
    margin-left: auto;
    margin-right: auto;
    width: 90%;
    background-color: #d0f0f6;
    text-align: left;
    padding: 8px;
}
</style>
</head>
<body>

<div class="container">
  <div class="center_div">
    <h1>Hello Friends</h1>
    <p>Welcome.This is a sample project to understand how to create a website.Enjoy navigating.</p>
  </div>
</div>



{% block content %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
<div style="margin-left:300px; margin-top:100px;">

 {% if form.errors %}
   <p class="error">Sorry, this is not a valid username or password</p>
 {% endif %}
<h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="white">Login Page</font></h1>
<div></div>
 <form action="/authcheck" method="post">{% csrf_token %}
 <label for="username"><b><font color="red">User name</font></b></label>
 <input type="text" name="username" value="" id="username"><br/><br/>
 <label for="password"><b><font color="red">Password</font></b></label>&nbsp;
 <input type="password" name="password" value="" id=password><br/><br/>
 <div>
  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
 <input type="submit" value="Login"/>
 &nbsp;
 <a href="/register"><font color="white">Sign Up</font></a></div></form>
 </div>
 {% endblock %}

 </body>
</html>

myblog/blog/templates/loggedin.html
<html>
<head>
{% load staticfiles %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'images/styles.css' %}" />
<div style="margin-left:480px; margin-top:10px;">
</head>
<body>
<h2>{{ post.title }}</h2>

<div class="content">
    <p>
        {{ post.text }}
   
</div>

{% if post.comment_set.all %}
<h2>Comments</h2>
<div class="comments">
    {% for comment in post.comment_set.all %}
        <span>
           <h4> {{ comment.name }} </h4>
        </span>
         <span>
         <p> 
           <textarea rows="3" cols="50">
{{ comment.text }}
            </textarea>
         </p>
         </span>
    {% endfor %}
</div>
{% endif %}

<br />

<h2>Add Comment</h2>

<form action="{% url 'logg' post.id %}" method="post">
    
   
        {{ textform.text }}<br/>
    <input type="submit" value="Submit" />
    <td><a href="/logout">Logout</a></td>
</form>
</body>
</html>

myblog/blog/templates/logout.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'styles2.css' %}" />
<body style="background-image: url({% static "logoutbackground.jpg" %})">
	<div style="margin-left:450px; margin-top:180px;">
<h1> <font color="red">Logout Successful</font> </h1>
<td><a href="/index">Login again?</a></td>

myblog/blog/templates/ok.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css/background' %}" />
<body style="background-image: url({% static "background.jpg" %})">
	<div style="margin-left:450px; margin-top:180px;">
<h1>Profile Updation Success</h1>
<td><a href="/index">Go Home</a></td>

myblog/blog/templates/profile.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css/background3' %}" />
<body style="background-image: url({% static "background3.jpg" %})">
	<div style="margin-left:480px; margin-top:210px;">
<h3>Hi {{full_name.capitalize}} you are now logged in!</h3>
<p>Click <a href="/eventlist">here</a> to see the events </p>
<p>Click <a href="/editprofile">here</a> to edit your profile</p>
<br/>
<br/>
<br/>
<table>
<tr>
<td>Name:</td>
<td>{{full_name.capitalize}}</td>
</tr>
<tr>
<td>Address:</td>
<td>{{address}}</td>
</tr>
<tr>
<td>Phone:</td>
<td>{{phone}}</td>
</tr>
</table>

myblog/blog/templates/register.html
{% block content %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css/background2' %}" />
<body style="background-image: url({% static "background2.jpg" %})">
	<div style="margin-left:480px; margin-top:210px;">
<h2>Sign up</h2>
<form action="/register" method="post">
{% if registered %}
<h3><font color="Red">Thank you for registering</font></h3>
{% else %}
<table>
<tr>
<td>Name:</td>
<td>{{profile_form.name}}{{profile_form.name.errors}}</td>
</tr>
<tr>
<td>Address:</td>
<td>{{profile_form.address}}{{profile_form.address.errors}}</td>
</tr>
<tr>
<td>Phone:</td>
<td>{{profile_form.phone}}{{profile_form.phone.errors}}</td>
</tr>
<tr>
<td>Username:</td>
<td>{{user_form.username}}</td>
</tr>
<tr>
<td>Password</td>
<td>{{user_form.password}}</td>
</tr>
<tr>
<td><input type="submit" value="Register"/></td>
<td>I will<a href="/index"> register </a>later</td>
</tr>
</table>
</form>
{%endif%}
{%endblock%}